# Copyright 2023 Yoshi Yamaguchi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: "golang:1.25"
    script: |
      GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@latest
      cp /go/bin/builder /workspace/builder
    id: DOWNLOAD_OCB
    waitFor: ["-"]

  - name: "golang:1.25"
    script: |
      pwd
      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOOS=linux GOARCH=amd64 /workspace/builder --config=/workspace/otelcol-builder.yaml --name=otelcol-custom-linux
    id: BUILD_COLLECTOR_LINUX
    waitFor: ["DOWNLOAD_OCB"]

  - name: "golang:1.25"
    script: |
      pwd
      CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 /workspace/builder --config=/workspace/otelcol-builder.yaml --name=otelcol-custom-macos
    id: BUILD_COLLECTOR_MACOS
    waitFor: ["DOWNLOAD_OCB"]

artifacts:
  objects:
    location: "gs://yoshifumi-artifacts/"
    paths:
      - "otelcol-custom-linux"
      - "otelcol-custom-macos"
