name: Feature request
description: Suggest an idea for this project
labels:
  - "feature request"
  - "needs triage"
body:
  - type: dropdown
    id: component
    attributes:
      label: Components
      description: Which component(s) does this feature request relate to?
      multiple: true
      options:
        - receiver/discord
        - documentation
        - CI/CD
        - other
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description the feature request is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
